CREATE DATABASE node_test;

USE node_test;

CREATE TABLE IF NOT EXISTS `users` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, `name` VARCHAR(50) NOT NULL, `age` INT(3) NOT NULL, PRIMARY KEY (`id`)
);

SELECT * FROM users LIMIT 100

TRUNCATE TABLE users;